require 'bundler/setup'
Bundler.require
# require_all 'app'
require 'pry'
require_relative '../app/models/User'
require_relative '../app/models/Recipe'
require_relative '../app/models/RecipeCard'
require_relative '../app/models/Ingredient'
require_relative '../app/models/RecipeIngredient'
require_relative '../app/models/Allergen'
